name: Run linter

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: x64
      - name: Setup reviewdog
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
      - name: Install dependencies
        run: |
          pip install -U pip tox wheel setuptools coveralls coverage[toml]
          pip install .[check]
      - name: run reviewdog
        run: |
          reviewdog -runners=flake8,mypy -reporter=github-pr-review -conf=.reviewdog.yml
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    name: Document checks
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: x64
      - name: Install dependencies
        run: |
          pip install -U pip tox wheel setuptools setuptools_scm[toml]
      - name: docs build and link check
        run: |
          tox -e docs
